export const API_ENDPOINTS = {
  GET_USER: 'https://cardify.app/api/get_user',
  REGISTER_USER: 'https://cardify.app/api/register_user', // New endpoint for registration
  CREATE_CARD: 'https://cardify.app/api/create_card',
  GET_CARDS_BY_USER: 'https://cardify.app/api/get_cards_by_user',
  GET_CARD_DETAILS: 'https://cardify.app/api/get_card_details',
  ADD_PARTICIPANT: 'https://cardify.app/api/add_participant',
  GET_PARTICIPANTS: 'https://cardify.app/api/get_participants',
  REMOVE_PARTICIPANT: 'https://cardify.app/api/remove_participant',
  UPDATE_CARD_STATUS: 'https://cardify.app/api/update_card_status',
  ADD_MESSAGE: 'https://cardify.app/api/add_message',
  GET_MESSAGES: 'https://cardify.app/api/get_messages',
  DELETE_MESSAGE: 'https://cardify.app/api/delete_message',
  EDIT_MESSAGE: 'https://cardify.app/api/edit_message',
  GET_AI_SUGGESTION: 'https://cardify.app/api/get_ai_suggestion',
  DELETE_CARD: 'https://cardify.app/api/delete_card',
  UPDATE_USER_PROFILE: 'https://cardify.app/api/update_user_profile',
  CHANGE_PASSWORD: 'https://cardify.app/api/change_password',
  GET_USER_DETAILS: 'https://cardify.app/api/get_user_details',
  GET_CARDS_BY_PARTICIPANT: 'https://cardify.app/api/get_cards_by_participant',
}
